---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: ./vpc_setup
      
    - name: Create Bharath VPC 
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
     
    - debug: 
        var: vpcout
    - name: Create public subnet1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr_block: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: Bharath-pubsub1
      register: pubsub1_out
      
